package guard

import (
	"crypto/sha256"
	"encoding/hex"
	"testing"

	_ "github.com/donislawdev/TestingFilesGenerator/internal/format/all"
	"github.com/donislawdev/TestingFilesGenerator/internal/preset"
)

// What a preset ejects is bytes somebody else's manifest remembers.
//
// The manifest carries a recipe_hash, computed from the source a run consumed,
// and a preset's source is what eject prints - the same bytes, which is the
// whole of PR5. So a tidy-up that moved a space would tell everyone holding a
// record from an earlier run that their recipe had changed, and nothing in this
// tree would have said a word.
//
// PRESET-FEASIBILITY-2026-09-08.md section 5 asked for a measured gate on
// exactly one refactor: pulling the set a declared limit produces out of
// size-boundaries so that upload-validation could use it too. The measurement
// was taken by hand on 2026-09-08 and again either side of that move on
// 2026-09-22, both times 1298 B and this sum. This is that measurement kept.
//
// Every preset since 2026-09-24, and a refusal's words as well as a source's
// bytes. Until then only size-boundaries was pinned, and the change that day
// was to how the other four work their sets out: asking the format for its
// smallest size once rather than for every file, and planning a file the set
// holds twelve times once (docs/GUI-MEMORY-2026-09-23.md section 4j). Neither
// may move a byte, so the gate came first and was measured on the tree before
// the change. The cases are the ones that reach what changed - other formats
// in allow, which ask for other floors, a limit small enough that a refusal
// names the floor, and a spread narrow enough to reach it.
//
// What to do when it goes red: decide, rather than update. The sum moving is a
// breaking change under D11 - a major, a Breaking entry in the changelog, and
// the owner's decision, because untouchable rule 12 says the assistant does not
// raise the version. A refactor that moved it is a refactor to undo.
//
// Decided once, on 2026-09-25: every sum here moved, because an ejected recipe
// now says what each target is for (the purpose key, which PR5 puts in the
// recipe rather than beside it). The owner's call was a Changed entry and no
// major - D11 is about the bytes of the files, and not one of them moved,
// which the guards on generated bytes hold. What did move is the recipe_hash
// of every run from a preset. docs/PRESET-INSTRUCTIONS-2026-09-25.md section 6.
func TestEjectingAPresetGivesTheBytesItAlwaysGave(t *testing.T) {
	// bytes and sum are the whole document, refused the whole refusal. The
	// first row was measured 2026-09-08, the rest on 2026-09-24 before the
	// change they guard, and every sum again on 2026-09-25 when the purposes
	// arrived - see above.
	pinned := []struct {
		id      string
		args    preset.Args
		bytes   int
		sum     string
		refused string
	}{
		{id: "size-boundaries", args: preset.Args{"format": "pdf", "limit": "10mb"}, bytes: 2629, sum: "f0307b6325a227364fdcb81620d5029b1491447f7cc055aa99e06aa51aa33f54"},
		{id: "size-boundaries", args: preset.Args{"format": "png", "limit": "1mb"}, refused: "the preset size-boundaries cannot build this set - under_1mb would be 0 B, and a file cannot be smaller than nothing. Raise the limit above 1048650 B, narrow the spread, or choose a format with a smaller minimum. The limit asked for was 1048576 B."},
		{id: "size-boundaries", args: preset.Args{"format": "jpg", "limit": "10mb"}, bytes: 2489, sum: "6b8cd2e300de5f670a5c702e0145ef69d9965b9d43ed283943fbc3218efa8111"},
		{id: "size-boundaries", args: preset.Args{"format": "jpg", "limit": "2kb", "spread": "1kb"}, bytes: 1182, sum: "cbbb4f47bd0eca3846cf2c4f2f599a0c801287e361722798ce565ae3dd6c4b45"},
		{id: "size-boundaries", args: preset.Args{"format": "jpg", "limit": "300", "spread": "100"}, refused: "the preset size-boundaries cannot build this set - under_100 would be 200 B and the smallest JPG this build makes is 602 B. Raise the limit above 702 B, narrow the spread, or choose a format with a smaller minimum. The limit asked for was 300 B."},
		{id: "upload-validation", args: preset.Args{}, bytes: 8220, sum: "735f46d99eaf038ae050448a0277777e8511e2bea384506bc0299633c5cb4d9e"},
		{id: "upload-validation", args: preset.Args{"limit": "5mb"}, bytes: 8208, sum: "1d190c8e6a87b6ea09a8441759221cc3462b1baadaa09cb8a2809963ef5b55c3"},
		{id: "upload-validation", args: preset.Args{"limit": "3kb"}, refused: "the preset upload-validation cannot build this set - allowed_pdf would be 1536 B and the smallest PDF this build makes is 3415 B. Raise the limit to 6830 B or more, or take pdf out of the allowed types. The limit asked for was 3072 B."},
		{id: "upload-validation", args: preset.Args{"allow": "docx,gif"}, bytes: 7618, sum: "1c4ffcc64e820f8384b98bc2b279df4fc0b16163e18f056fd9210f99fe879b1c"},
		{id: "upload-validation", args: preset.Args{"allow": "xlsx,ico,wav"}, bytes: 8254, sum: "5c2326e18ac1fe3c076a2391eed6f4819de60ec3726db2dc052872f1195dace0"},
		{id: "upload-validation", args: preset.Args{"bulk": "3", "far-over": "off"}, bytes: 7858, sum: "51b3271ed9c474af8f3c94ae9b38b82bf49b2bbcbfd67d6988259683df6f9024"},
		{id: "upload-validation", args: preset.Args{"deny": "exe,js"}, bytes: 7622, sum: "237f17d9907ce228c7928de6362ef6e47ef9d0c14467a10e5d2e7cfc247a7233"},
		{id: "tabular-import", args: preset.Args{}, bytes: 6045, sum: "e3d5ef9cc2633d05654b4bee16d62b61a30a776ff7a38cbdf35b3b073e18972e"},
		{id: "tabular-import", args: preset.Args{"rows": "100"}, bytes: 6042, sum: "7187e6a619e46a6f376361af433a45f9f4035c06f185c3cce7836179a3d4c2c0"},
		{id: "tabular-import", args: preset.Args{"columns": "5"}, bytes: 6042, sum: "81b712fe1186372ffdbf0d7c92ca753e5fac0f9083bb101695c4f0d37d8d4644"},
		{id: "text-encoding", args: preset.Args{}, bytes: 9263, sum: "322c2e02b446b0280555728f8401156d1569cd3046e57dc3af54bc0a2fde28aa"},
		{id: "text-encoding", args: preset.Args{"sample": "8kb"}, bytes: 9263, sum: "897a487c6d9eebaa1ff7d9bae44f17aec4bfcbd30597586f0b7b22eadb473ecd"},
		{id: "empty-and-minimal", args: preset.Args{}, bytes: 8966, sum: "3e815fffad3da06d1d8333111ae2ccaa1d325172d87c6d49e2177249808083fe"},
		{id: "empty-and-minimal", args: preset.Args{"formats": "jpg,png,txt"}, bytes: 1472, sum: "19b12800372395ad3bf5cba6407ca654d7ed51eba3a5bc5436f76a94bc09253c"},
		// The preset of unusual file names, measured 2026-09-25 on its first
		// build: the default, and a format whose extension is a byte longer,
		// since the names about length are made to a length with it.
		{id: "filename-handling", args: preset.Args{}, bytes: 18983, sum: "f720c4a54c5fc17fea553a084fd13aaff4150c2fce5a4d953b10aee137ebe021"},
		{id: "filename-handling", args: preset.Args{"format": "docx"}, bytes: 19077, sum: "94a40d97bf549cbdd3e7ccaafe3372d7962ad542f358d37a2d945445c95d6f43"},
	}

	for _, want := range pinned {
		expanded, err := preset.Expand(want.id, want.args)
		if want.refused != "" {
			if err == nil || err.Error() != want.refused {
				t.Errorf("%s at %v was refused with\n  %q\nuntil now, and now gives\n  %v", want.id, want.args, want.refused, err)
			}
			continue
		}
		if err != nil {
			t.Errorf("%s refused %v: %v", want.id, want.args, err)
			continue
		}
		sum := sha256.Sum256(expanded.Source)
		got := hex.EncodeToString(sum[:])
		if len(expanded.Source) == want.bytes && got == want.sum {
			continue
		}
		t.Errorf("ejecting %s at %v gives %d B and %s, and it has given %d B and %s until now.\n"+
			"Every manifest written from this preset carries a hash of these bytes, so this is a "+
			"breaking change under D11 rather than a number to update here.\n%s",
			want.id, want.args, len(expanded.Source), got, want.bytes, want.sum, expanded.Source)
	}
}
