package guard

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/donislawdev/TestingFilesGenerator/internal/format"
	_ "github.com/donislawdev/TestingFilesGenerator/internal/format/all"
)

// The README tells a reader which settings each format takes, and until
// 2026-09-03 nothing asked whether that was true. It was not, on seven rows -
// O176 in docs/OBSERVATIONS.md has the measurement.
//
// The shape of the drift is worth naming, because it is not carelessness. The
// table is the last thing anybody thinks of when a setting is added: the
// registry declares it, the window draws it, tfg formats prints it, the site is
// regenerated by its own guard, and the README sits outside all of that. So it
// went stale four times in a row without one red run. log said "none" while
// carrying eight settings, zip and targz listed three of eight, and avif and
// jxl had no row at all.
//
// The site has had this guard since it was built - TestTheSiteSaysWhatTheToolSays
// renders the format table from the registry and compares it against what is
// published. This is the same promise for the one page a visitor reads first.
//
// Sets rather than sequences, deliberately. Whether a row reads "width, height"
// or "height, width" is a question about prose, and a guard that answered it
// would be refusing English rather than catching a lie. What it refuses is a
// setting named that does not exist, a setting that exists and is not named,
// and a format missing from the table altogether.
func TestTheReadmeSettingsTableAgreesWithTheRegistry(t *testing.T) {
	rows := readmeSettingsTable(t)
	if len(rows) == 0 {
		t.Fatal("the per format settings table has no rows - this guard would pass against any README ever written")
	}

	descriptors := format.All()
	if len(descriptors) == 0 {
		t.Fatal("no format is registered - this guard would pass without checking anything")
	}

	declared := map[string][]string{}
	for _, d := range descriptors {
		names := make([]string, 0, len(d.Properties))
		for _, p := range d.Properties {
			names = append(names, p.Name)
		}
		sort.Strings(names)
		declared[d.ID] = names
	}

	seen := map[string]string{}
	for _, row := range rows {
		for _, id := range row.formats {
			if _, ok := declared[id]; !ok {
				t.Errorf("the README settings table names the format %q and nothing registers it", id)
				continue
			}
			if where, twice := seen[id]; twice {
				t.Errorf("%s is in the settings table twice, here and in the row for %s - "+
					"two rows can disagree, and the one a reader believes is whichever they read first", id, where)
				continue
			}
			seen[id] = strings.Join(row.formats, ", ")

			want := declared[id]
			got := append([]string(nil), row.settings...)
			sort.Strings(got)
			if strings.Join(got, ",") != strings.Join(want, ",") {
				t.Errorf("the README says %s takes %s and the registry declares %s. "+
					"Fix the table rather than this guard - a reader who is told a format has no settings "+
					"does not go and check", id, listOrNone(got), listOrNone(want))
			}
		}
	}

	for id := range declared {
		if _, ok := seen[id]; !ok {
			t.Errorf("%s is registered and the README settings table has no row for it, so its settings "+
				"are documented nowhere a reader of that page would look", id)
		}
	}
}

// The list a reader meets first names every format there is.
//
// Separate from the settings table above because it is a different promise and
// it went stale on its own: jxl was added on 2026-08-31 as the twenty fourth
// format and never reached this list, so the page a visitor lands on offered
// twenty three while the binary shipped twenty four. Nothing was asking.
//
// One direction only, and that is deliberate rather than lazy. The table names
// formats that exist, so a registered format missing from it is a lie. The
// other direction - a name in the table that nothing registers - is already
// refused by the settings table below it, which every format has to appear in
// too, and asking twice here would put the same claim in two places.
//
// What this does NOT check is the COUNT in the sentence above the table,
// which is spelled out in words. That is left alone on purpose: the copied
// numbers guard measured the general form of it on 2026-08-05, raised 43
// findings and found most of them false, because "24 formats" and "25 formats"
// and "150 formats" answer three different questions in this repository. The
// count in that one sentence stays on the reader. The counts the README writes
// in DIGITS are a narrower question with one answer, and the guard below asks
// it.
func TestTheReadmeListsEveryFormatItShips(t *testing.T) {
	body, err := os.ReadFile(filepath.Join(repoRoot(t), "README.md"))
	if err != nil {
		t.Fatalf("reading the README: %v", err)
	}
	const heading = "## 📁 Formats it generates"
	text := string(body)
	start := strings.Index(text, heading)
	if start < 0 {
		t.Fatalf("the README has no %q heading, so this guard has nothing to read", heading)
	}
	end := strings.Index(text[start+len(heading):], "\n## ")
	if end < 0 {
		t.Fatal("the formats section runs to the end of the README, which means the heading after it moved")
	}
	section := text[start : start+len(heading)+end]

	listed := map[string]bool{}
	for _, name := range spansIn(section) {
		listed[name] = true
	}
	if len(listed) == 0 {
		t.Fatal("the formats section names nothing - this guard would pass against any README ever written")
	}

	descriptors := format.All()
	if len(descriptors) == 0 {
		t.Fatal("no format is registered - this guard would pass without checking anything")
	}
	for _, d := range descriptors {
		if !listed[d.ID] {
			t.Errorf("%s is registered and the list under %q does not name it, so the first page a "+
				"visitor reads offers fewer formats than the binary ships", d.ID, heading)
		}
	}
}

// Every count of formats the README writes in digits is the number the
// program registers.
//
// Measured 2026-09-25: the README said "24 formats" and "24 real formats"
// while the binary shipped 26, a release after yaml and toml arrived. The
// same release had moved the count in words above the table to "Twenty six",
// by hand, and nothing compared the other two with anything - the site gets
// its number from the registry, the README cannot. So this asks the one
// question those phrases answer, and only for the README, where a digit next
// to "formats" means one thing.
func TestTheReadmeCountsTheFormatsItShips(t *testing.T) {
	body, err := os.ReadFile(filepath.Join(repoRoot(t), "README.md"))
	if err != nil {
		t.Fatalf("reading the README: %v", err)
	}
	shipped := len(format.All())
	if shipped == 0 {
		t.Fatal("no format is registered - this guard would pass without checking anything")
	}
	counts := regexp.MustCompile(`\b(\d+) (real )?formats\b`).FindAllStringSubmatch(string(body), -1)
	if len(counts) == 0 {
		t.Fatal("the README states no count of formats in digits, so this guard reads nothing - " +
			"if the counts were reworded on purpose, retire it")
	}
	for _, c := range counts {
		if c[1] != strconv.Itoa(shipped) {
			t.Errorf("the README says %q and the program ships %d formats", c[0], shipped)
		}
	}
}

// listOrNone words a list the way the table does, so a failure can be compared
// against the line it is about without translating between two spellings.
func listOrNone(names []string) string {
	if len(names) == 0 {
		return "none"
	}
	return strings.Join(names, ", ")
}

// settingsRow is one line of the table: the formats it speaks for, and what it
// says they take.
type settingsRow struct {
	formats  []string
	settings []string
}

var codeSpan = regexp.MustCompile("`([^`]+)`")

// readmeSettingsTable reads the table under its own heading.
//
// Anchored on the heading rather than on "the first table with two columns",
// because the README holds several two column tables and a guard that found the
// wrong one would be green about something nobody asked.
func readmeSettingsTable(t *testing.T) []settingsRow {
	t.Helper()
	const heading = "### Per format settings"

	body, err := os.ReadFile(filepath.Join(repoRoot(t), "README.md"))
	if err != nil {
		t.Fatalf("reading the README: %v", err)
	}
	text := string(body)

	start := strings.Index(text, heading)
	if start < 0 {
		t.Fatalf("the README has no %q heading, so this guard has nothing to read. "+
			"If the section was renamed, rename it here too rather than deleting the check", heading)
	}

	var rows []settingsRow
	for _, line := range strings.Split(text[start+len(heading):], "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "|") {
			// The table has ended. Anything after it belongs to another
			// section, so reading on would collect unrelated tables.
			if len(rows) > 0 {
				break
			}
			continue
		}
		cells := strings.Split(strings.Trim(line, "|"), "|")
		if len(cells) != 2 {
			continue
		}
		formats := spansIn(cells[0])
		if len(formats) == 0 {
			// The header row and the dashes under it.
			continue
		}
		rows = append(rows, settingsRow{formats: formats, settings: spansIn(cells[1])})
	}
	return rows
}

// spansIn pulls the code spans out of one cell, which is how both halves of the
// table name things.
func spansIn(cell string) []string {
	var out []string
	for _, m := range codeSpan.FindAllStringSubmatch(cell, -1) {
		out = append(out, strings.TrimSpace(m[1]))
	}
	return out
}
